# Errores en métodos numéricos
## Definiciones y estándares con respecto a los errores y precisión numérica
Para medir los errores numéricos usamos la nomenclatura de los errores experimentales. Por ejemplo, usamos la notación de dar el valor resultante $\pm$ el error.

In [1]:
from random import *
l = []
for i in range(10):
    x = uniform(0.8,2.8) #valores flotantes aleatorios en el intervalo
    l.append(x)
    
n = len(l)
suma = 0
for i in range(n):
    suma += l[i]
promedio =suma/n

error = max(l)-min(l)
print('El promedio resultante es: \n',promedio,'+-',error)

El promedio resultante es:
 1.8579404955474512 +- 1.7246971163365148

### Error absoluto, error relativo y error porcentual

In [3]:
from math import *
def error_abs(real,approx):
    return abs(real-approx)
def error_rel(real,approx):
    return (abs(real-approx))/real
def error_por(real,approx):
    return ((abs(real-approx))/real)*100

x_teo=e
x_aprox=19/7

e_abs=error_abs(x_teo,x_aprox)
e_rel=error_rel(x_teo,x_aprox)
e_por=error_por(x_teo,x_aprox)

### Errores numéricos de la aritmética discreta
Hay que considereae que la compitadora tiene limitacines. Las computadoras no pueden guardadr números con decimales infinitos, por lo que no se pude manipular elementos continuos, sino que toda la matemática que se haga con la computadora serán discretas. Tampoco números muy grandes o muy chicos.

In [5]:
x = 1.1 + 2.2
epsilon = 1e-12 #toleracion
if abs(x-3.3)<epsilon:
    print(x)

3.3000000000000003

In [9]:
#Primero veamos el paquete decimal
from decimal import *
from math import *
print(1/7.)
getcontext().prec = 6
print((Decimal(1)/Decimal(7)))
getcontext().prec = 60
print((Decimal(1))/Decimal(7))
getcontext().prec = 15
print(sin(Decimal(2)))

0.14285714285714285
0.142857
0.142857142857142857142857142857142857142857142857142857142857
0.9092974268256817

## Ejemplo
Evaluamos $f(x)=x(sqrt(x+1)+sqrt(x))$ con una calculadora de 6 dígitos de precisión.

In [14]:
from decimal import Decimal as D, getcontext as C 
import pandas as pd
from math import *

C().prec = 6

def f(x): #getcontext es 16 cifras significativas 
    return x*(sqrt(x+1)-sqrt(x))
def fd(x):
    return x*(C().sqrt(x+D(1))-C().sqrt(x))
residuo = []
idx = []
for i in range(10):
    x = 10**i
    idx.append(x)
    residuo.append([fd(D(x)),f(x)])
#print(residuo)
cols = ["Aprox","Real"]
pd.DataFrame(residuo,index=idx,columns=cols)

              Aprox          Real
1           0.41421      0.414214
10          1.54340      1.543471
100          4.9900      4.987562
1000        15.8000     15.807437
10000        50.000     49.998750
100000      100.000    158.113488
1000000           0    499.999875
10000000       0.00   1581.138790
100000000         0   5000.000056
1000000000      0.0  15811.390767

In [15]:
from decimal import Decimal as D, getcontext as C 
import pandas as pd
from math import *

C().prec = 10

def f1(x): #getcontext es 16 cifras significativas 
    return (1-cos(x)) / (x*x)
def f1d(x):
    return +D(D(1) - (+D(cos(x)))) / (D(x*x))

residuo = []
idx = []
for i in range(1,7):
    x = 10**(-i)
    idx.append(x)
    err = abs(float(f1d(+D(x)))-f1(x))
    residuo.append([f1d(+D(x)),f1(x),err*100])
#pd.set_option("precision",C().prec)
cols = ["Aprox","Real","%"]
pd.DataFrame(residuo,index=idx,columns=cols)

               Aprox      Real             %
0.100000  0.49958347  0.499583  2.197418e-07
0.010000    0.499996  0.499996  1.666526e-05
0.001000         0.5  0.500000  4.167450e-06
0.000100         0.5  0.500000  3.038735e-07
0.000010           1  0.500000  5.000000e+01
0.000001       0E+12  0.500044  5.000445e+01

## Underflow y Overflow
LA capacidad que tiene la máquina para hacer el proceso. A la fecha el flotante más grande que se puede ingresar es 10^308 y para números muy pequeños es 2^-1022

In [26]:
from math import sqrt
#Ejercicio
x = 1
y = 1 + 1e-20*sqrt(2)

raiz2 = sqrt(2)
raiz22 = 1e20*(y-x)

print(raiz2,raiz22,error_por(raiz2,raiz22))

1.4142135623730951 0.0 100.0

# Repaso
Vamos a tratar a los errores numéricos como errores de laboratorio. Estos errores se propagan como: $\epsilon_{Tot} = \epsilon_{num} + \epsilon_{APF}$ 

Donde APF es Aritmética de Punto Flotante. Para esto utilizamos el módulo $\bf{Decimal}$, que era algo complicado de utilizar pues es un módulo que cambian constantemente. Como default Python tiene la precisión de $c = 1 \times 10^{-16}$

In [1]:
#Primero veremos el módulo Decimal
from decimal import *
from math import*

print(1/7)
getcontext().prec = 6
print(Decimal(1)/Decimal(7)) #Decimal calcula con la precisión de getcontext
getcontext().prec = 60
print(1/7)
print(Decimal(1)/Decimal(7))

0.14285714285714285
0.142857
0.14285714285714285
0.142857142857142857142857142857142857142857142857142857142857

## Ejemplo

In [2]:
from decimal import Decimal as D, getcontext as C 
import pandas as pd
from math import *

C().prec = 10

def f1(x): #getcontext es 16 cifras significativas 
    return (1-cos(x)) / (x*x)
def f1d(x):
    return +D(D(1) - (+D(cos(x)))) / (D(x*x))

# + - D indicador de la prec sustituye el contexto
residuo = []
idx = []
for i in range(1,7):
    x = 10**(-i)
    idx.append(x)
    err = abs(float(f1d(+D(x)))-f1(x))
    residuo.append([f1d(+D(x)),f1(x),err*100])
#pd.set_option("precision",C().prec)
cols = ["Aprox","Real","Error %"]
pd.DataFrame(residuo,index=idx,columns=cols) #Data Frame recibe (tabla c info a desplegar, índices,título de columnas)

               Aprox      Real       Error %
0.100000  0.49958347  0.499583  2.197418e-07
0.010000    0.499996  0.499996  1.666526e-05
0.001000         0.5  0.500000  4.167450e-06
0.000100         0.5  0.500000  3.038735e-07
0.000010           1  0.500000  5.000000e+01
0.000001       0E+12  0.500044  5.000445e+01

In [ ]:
from math import exp,factorial
c().prec = 4
res = +D(1)
for i in range(1,26):